apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: phpipam-cron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpipam-cron
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpipam-cron
    spec:
      containers:
        - env:
            - name: IPAM_DATABASE_HOST
              value: mysql
            - name: IPAM_DATABASE_PASS
            - name: IPAM_DATABASE_USER
            - name: IPAM_DISABLE_INSTALLER
              value: "1"
            - name: SCAN_INTERVAL
              value: 1h
            - name: TZ
              value: America/Sao_Paulo
          image: phpipam/phpipam-cron:latest
          name: phpipam-cron
          volumeMounts:
            - mountPath: /usr/local/share/ca-certificates
              name: phpipam-cron-pvc
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: phpipam-cron-pv
          persistentVolumeClaim:
            claimName: phpipam-cron-pvc
            readOnly: true
